import localFont from 'next/font/local'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const firaSans = localFont({
  src: [
    {
      path: '../customFonts/FiraSans-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../customFonts/FiraSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../customFonts/FiraSans-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../customFonts/FiraSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={firaSans.className}>{children}</body>
    </html>
  )
}
