name: Test and Smoke

on:
  pull_request:
  push:

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Smoke build and start
        run: |
          npm run build
          npm start &
          PID=$!
          sleep 5
          curl -f http://localhost:3000
          kill $PID

